version: "3.7"

services:
  paper:
    image: ghcr.io/sksat/papermc-docker:1.17.1@sha256:b71c7de2935c0fa18c3599f9c315abc6b794f3220233ceb21937413a106c4478
    restart: always
    depends_on:
      - db

    stdin_open: true
    ports:
      - 9225:9225
      - 25565:25565
      - 25575:25575
    environment:
      JAVA_TOOL_OPTIONS: "-Xms2G -Xmx2G"
    volumes:
      - ./data:/app

  db:
    image: mysql:8.0.26
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "mysql-root-password"
      MYSQL_DATABASE: "itemcount"
    volumes:
      - ./iscount_data:/var/lib/mysql

  item-count-exporter:
    image: githubfree/sql_exporter:0.5
    depends_on:
      - db

    ports:
      - "9226:9399"
    volumes:
      - ./item-count-exporter/sql_exporter.yml:/sql_exporter.yml
      - ./item-count-exporter/item_count.collector.yml:/item_count.collector.yml
