version: "3.7"

services:
  paper:
    image: ghcr.io/sksat/papermc-docker:1.17.1@sha256:8587567d27f3c37eb10b25247db709ea9f309daabd41141554858836fdb4b870
    restart: always
    depends_on:
      - db

    stdin_open: true
    ports:
      - 9225:9225
      - 25565:25565
      - 25575:25575
    environment:
      JAVA_TOOL_OPTIONS: "-Xms2G -Xmx2G"
    volumes:
      - ./data:/app

  paper-tunnel:
    image: cloudflare/cloudflared:2021.11.0
    restart: always
    volumes:
      - ./cloudflared:/etc/cloudflared
    command: tunnel --hostname mc-tunnel.sksat.net --url tcp://paper:25565 --loglevel info

  db:
    image: mysql:8.0.27
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "mysql-root-password"
      MYSQL_DATABASE: "itemcount"
    volumes:
      - ./iscount_data:/var/lib/mysql

  item-count-exporter:
    image: githubfree/sql_exporter:0.5
    depends_on:
      - db

    ports:
      - "9226:9399"
    volumes:
      - ./item-count-exporter/sql_exporter.yml:/sql_exporter.yml
      - ./item-count-exporter/item_count.collector.yml:/item_count.collector.yml
