version: "3.7"

services:
  paper:
    image: ghcr.io/sksat/papermc-docker:1.17.1@sha256:c828f55aaf146e5fc684ee7e09ac436677688369c828fce922c9e74a79ca9715
    restart: always

    stdin_open: true
    ports:
      - 9225:9225
      - 25565:25565
      - 25575:25575
    environment:
      JAVA_TOOL_OPTIONS: "-Xms2G -Xmx2G"
    volumes:
      - ./data:/app
